name: "update: requirements.txt"

on: 
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv requirements
    - name: Commit if update requirements
      run: |
        git config user.name bot
        git config user.email bot@github.com

        if git diff --quiet; then
          echo "No hay cambios."
        else
          git add requirements.txt
          git commit -m "Update requirements.txt based this commit -> $(git rev-parse --short HEAD)"
          git push origin main
        fi
